'use strict';const test=require('node:test'),assert=require('node:assert/strict'),P=require('../domain/zoningPolicy');const{readiness,requireProviders}=require('../services/providerBoundary');const hash=c=>c.repeat(64);
function source(overrides={}){return{sourceId:'z1',registryRef:'city-code:12.3',jurisdiction:'Metro City',ruleVersion:'2026.1',title:'Mixed Use District Code',contentDigest:hash('a'),signatureDigest:hash('b'),effectiveFrom:'2026-01-01',effectiveTo:null,classification:'public',authorityRank:1,...overrides};}
function sources(){return[P.validateSource(source(),'2026-07-01').source,P.validateSource(source({sourceId:'map1',registryRef:'gis:parcel',ruleVersion:'map-2026',title:'Official zoning map',contentDigest:hash('c')}),'2026-07-01').source];}
test('sources require jurisdiction, effective date, signatures, provenance, and privilege basis',()=>{assert.equal(P.validateSource(source(),'2026-07-01').ok,true);const stale=P.validateSource(source({effectiveTo:'2026-01-31',classification:'privileged'}),'2026-07-01');assert.equal(stale.ok,false);assert.match(stale.errors.join(' '),/not effective/);assert.match(stale.errors.join(' '),/privilege/);});
test('conflicting sources require an attested qualified resolution',()=>{const a=P.validateSource(source(),'2026-07-01').source,b=P.validateSource(source({sourceId:'z2',contentDigest:hash('d')}),'2026-07-01').source;assert.throws(()=>P.resolveRules([a,b],{}),/conflicting/);const result=P.resolveRules([a,b],{selectedSourceId:'z2',qualifiedReviewerId:'planner-1',attestationDigest:hash('e')});assert.deepEqual(result.conflicts,['2026.1']);assert.deepEqual(result.selectedSourceIds,['z2']);});
test('different jurisdictions cannot be combined',()=>{const rows=sources();rows[1].jurisdiction='Other City';assert.throws(()=>P.resolveRules(rows,{}),/jurisdiction/);});
test('zoning analysis calculates FAR, height, density, and setback against cited evidence',()=>{const rules=P.resolveRules(sources(),{}),parcel={parcelId:'p1',gisDigest:hash('f'),lotAreaSqFt:43560,proposal:{floorAreaSqFt:87120,heightFt:50,units:20,frontSetbackFt:15}},analysis=P.analyze(rules,parcel,{maxFar:2,maxHeightFt:60,maxUnitsPerAcre:25,minFrontSetbackFt:10});assert.equal(analysis.ok,true);assert.equal(analysis.analysis.compliant,true);assert.equal(analysis.analysis.findings.find(x=>x.code==='FAR').actual,2);assert.equal(analysis.analysis.nonAdviceNotice.includes('qualified'),true);});
test('adverse analysis preserves cited findings rather than predicting approval',()=>{const rules=P.resolveRules(sources(),{}),result=P.analyze(rules,{parcelId:'p1',gisDigest:hash('f'),lotAreaSqFt:43560,proposal:{floorAreaSqFt:130680,heightFt:90,units:40,frontSetbackFt:5}},{maxFar:2,maxHeightFt:60,maxUnitsPerAcre:25,minFrontSetbackFt:10});assert.equal(result.analysis.compliant,false);assert.deepEqual(result.analysis.findings.filter(x=>!x.passes).map(x=>x.code),['FAR','HEIGHT','DENSITY','FRONT_SETBACK']);});
test('privileged and confidential sources are redacted by matter-scoped role',()=>{const privileged=P.validateSource(source({classification:'privileged',privilegeBasis:'attorney-client'}),'2026-07-01').source;assert.equal(P.redact(privileged,{role:'matter_owner',matterPermission:true}).visible,false);assert.equal(P.redact(privileged,{role:'municipal_counsel',matterPermission:true}).visible,true);const confidential=P.validateSource(source({classification:'confidential'}),'2026-07-01').source;assert.equal(P.redact(confidential,{role:'qualified_planner',matterPermission:false}).reason,'matter_permission');});
test('copilot answers only from authorized cited analysis and always marks non-advice',()=>{const rows=sources(),rules=P.resolveRules(rows,{}),analysis=P.analyze(rules,{parcelId:'p1',gisDigest:hash('f'),lotAreaSqFt:43560,proposal:{floorAreaSqFt:43560,heightFt:30,units:5,frontSetbackFt:20}},{maxFar:2,maxHeightFt:60,maxUnitsPerAcre:25,minFrontSetbackFt:10}).analysis,response=P.copilot({question:'Does this fit?',analysis,sources:rows,actor:{role:'qualified_planner',matterPermission:true}});assert.equal(response.abstained,false);assert.equal(response.nonAdvice,true);assert.equal(response.citations.length,2);const hidden=P.copilot({question:'?',analysis,sources:[P.validateSource(source({classification:'privileged',privilegeBasis:'work product'}),'2026-07-01').source],actor:{role:'matter_owner',matterPermission:true}});assert.equal(hidden.abstained,true);});
test('deadlines are derived from cited rules',()=>{const due=P.deadline({triggerAt:'2026-07-01T12:00:00Z',days:30,ruleRef:'notice-30',sourceDigest:hash('a'),timezone:'America/New_York'});assert.equal(due.dueAt,'2026-07-31T12:00:00.000Z');assert.match(due.deadlineDigest,/^[a-f0-9]{64}$/);});
test('approval requires independent qualified review, deadline, and non-advice acknowledgement',()=>{const analysis={analysisDigest:hash('a')},due={deadlineDigest:hash('b')},input={matter:{id:1,state:'human_review',ownerId:1},analysis,deadline:due,review:{qualifiedReviewerId:2,attestationDigest:hash('c'),adviceDisclaimerAccepted:true}};assert.equal(P.approve(input).ok,true);const bad=P.approve({...input,review:{qualifiedReviewerId:1,attestationDigest:hash('c'),adviceDisclaimerAccepted:false}});assert.match(bad.errors.join(' '),/independent/);assert.match(bad.errors.join(' '),/non-advice/);});
test('filing delivery, recovery, and providers fail closed',()=>{assert.match(P.delivery({externalRef:'file-1',signedReceiptDigest:hash('d'),deliveredAt:'2026-07-02',status:'accepted'}).deliveryDigest,/^[a-f0-9]{64}$/);assert.deepEqual(P.retry(1),{status:'retry',retryable:true,nextDelaySeconds:30});assert.deepEqual(P.retry(5),{status:'dead_letter',retryable:false,nextDelaySeconds:null});assert.equal(readiness({}).ready,false);assert.throws(()=>requireProviders(['filing'],{}),/not ready/);});
